server:
  port: 60999 #本应用启动的 http 服务端口

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wowxhycoming/java.spring-cloud.git # github 仓库地址
          searchPaths: cloud-config-repository # 从仓库那个目录下读取文件