spring:
  application:
    # 应用名称
    name: cloud-biz-instance
server:
  # 服务端口
  port: 60011

eureka:
  instance:
    # 代表了一个启动示例的标识 自定义，可以显示在控制台上
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    # 服务是否注册到注册中心
    registerWithEureka: true
    # 是否获取注册中心注册服务的列表
    fetchRegistry: true
    serviceUrl:
      # 注册对应的eureka的默认域，一般添加对应注册中心地址
      defaultZone: ${project.eureka.server.default.zone}
